//ACTIVITIES
export const CREATE_ACTIVITY_START = "CREATE_ACTIVITY_START";
export const CREATE_ACTIVITY_SUCCESS = "CREATE_ACTIVITY_SUCCESS ";
export const CREATE_ACTIVITY_FAIL = "CREATE_ACTIVITY_FAIL";
export const CREATE_INIT = "CREATE_INIT";

export const GET_ACTIVITIES_LIST_START = "GET_ACTIVITIES_LIST_START";
export const GET_ACTIVITIES_LIST = "GET_ACTIVITIES_LIST";
export const GET_ACTIVITIES_LIST_SUCCESS = "GET_ACTIVITIES_LIST_SUCCESS";
export const GET_ACTIVITIES_LIST_FAIL = "GET_ACTIVITIES_LIST_FAIL";

export const MY_ACTIVITIES_START = "MY_ACTIVITIES_START";
export const MY_ACTIVITIES_FAIL = "MY_ACTIVITIES_FAIL";
export const MY_ACTIVITIES_SUCCESS = "MY_ACTIVITIES_SUCCESS";

export const DISPLAY_ACTIVITY = "DISPLAY_ACTIVITY";
export const DISPLAY_ACTIVITY_SUCCESS = "DISPLAY_ACTIVITY_SUCCESS";
export const DISPLAY_ACTIVITY_FAIL = "DISPLAY_ACTIVITY_FAIL";
export const DISPLAY_ACTIVITY_START = "DISPLAY_ACTIVITY_START";

export const JOIN_ACTIVITY = "JOIN_ACTIVITY";

//CONFIRMATION
export const CREATE_CONFIRMATION = "CREATE_CONFIRMATION";
export const CONFIRMED_ATTENDANCE = "CONFIRMED_ATTENDANCE";
//MODAL
export const MODAL_CLOSED = "MODAL_CLOSED";

//AUTH
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const SET_AUTH_USER = "SET_AUTH_USER";
export const AUTH_USER_FAIL = "AUTH_USER_FAIL";
export const RESET_AUTH_STATE = "RESET_AUTH_STATE";
export const SET_AUTH_USER_START = "SET_AUTH_USER_START";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
