export const CREATE_ACTIVITY_START = "CREATE_ACTIVITY_START";
export const CREATE_ACTIVITY_SUCCESS = "CREATE_ACTIVITY_SUCCESS ";
export const CREATE_ACTIVITY_FAIL = "CREATE_ACTIVITY_FAIL";

export const GET_ACTIVITIES_LIST_START = "GET_ACTIVITIES_LIST_START";
export const GET_ACTIVITIES_LIST = "GET_ACTIVITIES_LIST";
export const GET_ACTIVITIES_LIST_SUCCESS = "GET_ACTIVITIES_LIST_SUCCESS";
export const GET_ACTIVITIES_LIST_FAIL = "GET_ACTIVITIES_LIST_FAIL";

export const DISPLAY_ACTIVITY = "DISPLAY_ACTIVITY";
export const DISPLAY_ACTIVITY_SUCCESS = "DISPLAY_ACTIVITY_SUCCESS";
export const DISPLAY_ACTIVITY_FAIL = "DISPLAY_ACTIVITY_FAIL";
export const DISPLAY_ACTIVITY_START = "DISPLAY_ACTIVITY_START";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

// export const AUTH_START = "AUTH_START";
// export const AUTH_FAIL = "AUTH_FAIL";
// export const AUTH_SUCCESS = "AUTH_SUCCESS";
// export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const MY_ACTIVITIES_START = "MY_ACTIVITIES_START";
export const MY_ACTIVITIES_FAIL = "MY_ACTIVITIES_FAIL";
export const MY_ACTIVITIES_SUCCESS = "MY_ACTIVITIES_SUCCESS";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
//TEST
export const GET_ACTIVITIES = "GET_ACTIVITIES";
